### ISSUE TITLE
make fatal error

### ISSUE THREAD

**Issue by JohanvandenHeuvel** [panda-planner-dev/pandaPIgrounder#13]
Hi,

when trying to compile pandaPIgrounder it fails when running the `make` command.

See error message:

```
jvdheuvel@jvdheuvel-Lenovo:~/Documents/planning/hddl planners/panda/pandaPIgrounder/cpddl$ make
/bin/sh: 1: test: /home/jvdheuvel/Documents/planning/: unexpected operator
/bin/sh: 1: test: /home/jvdheuvel/Documents/planning/: unexpected operator
/bin/sh: 1: test: /home/jvdheuvel/Documents/planning/: unexpected operator
/bin/sh: 1: test: /home/jvdheuvel/Documents/planning/: unexpected operator
cc -O3 -Wall -pedantic --std=gnu99 -Wno-missing-braces -I.   -c -o .objs/lisp.o src/lisp.c
src/lisp.c:27:10: fatal error: boruvka/alloc.h: No such file or directory
   27 | #include <boruvka/alloc.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:70: .objs/lisp.o] Error 1
```

I did run all the previous steps, and also tried using build.sh

**Comment by galvusdamor** [comment]
Hi Johan,

This looks like an error that arises when cpddl generates its compile parameters. Normally, for the call to cc, there should be a second include after ``-I.`` -- the directory in which boruvka is located.
The error is likely caused by the ``cpddl/Makefile.include`` line 65 (an similar lines in 57, 83, and 105; thus you get the error four times). Why this crashed could have two options:
1) You seem to use sh instead of a newer shell, i.e., bash. If you have bash, you can set the shell variable SHELL=/path/to/bash and re-try. This should then use bash instead of sh
2) In ``Makefile.include``, in line 1, the ``BASEPATH_`` is defined. What could happen is that this somehow contains a space.
To check, can you add the lines
```
print:                                                                                                                                                                                                          
      @echo $(BASEPATH_) 
```
to the Makefile.include and just run ``make print``. This outputs the basepath.

Kind regards,
Gregor

**Comment by JohanvandenHeuvel** [comment]
Hello Gregor,

The issue was option 2, I had a space in a folder name: "hddl planners". I wouldn't have thought about that, based on the error message; so thanks a lot for the help!

Not sure about 1, my SHELL variable is bash. Maybe its using sh because of how `make` is installed for me, but I'm unfamiliar with `make`.
