### ISSUE TITLE
Empty grounding when using recursive task while should be a solution

### ISSUE THREAD

**Issue by AlexDmr** [panda-planner-dev/pandaPIgrounder#14]
Hello and thanks for your work on PandaPI.
I am defining a HDDL domain that use recursive tasks, the problem is that the grounder find that the domain is empty.
Basically, I am modeling a list of items, each item can be done or undone, I want to filter the list ro remove items that are done.
Using these files, the grounder (and thus the engine), cannot find a solution:
[domainRec.hddl.txt](https://github.com/panda-planner-dev/pandaPIgrounder/files/13704120/domainRec.hddl.txt)
[problemRec.pddl.txt](https://github.com/panda-planner-dev/pandaPIgrounder/files/13704121/problemRec.pddl.txt)

What surprise me is that if I uncomment line 57 and comment the line 58 in the domain file then The grounder is able to ground the problem and the engine ro produce a solution.
I do not understand why the grounder does seems to simplify the domain to impossible. Could you provide me with some hints ? Is it a limitation of Panda? a problem of HDDL modeling? Or maybe a bug on you side ?

Thanks for your help.

**Comment by galvusdamor** [comment]
Hi Alex,

Thanks for using pandaPI!

The problem here lies in line 41 of your file. This is the method that ends the recursion through the list - but critically it only allows for ending the recursion is the list is actually empty at the end - in your modelling if the listStart and listEnd share a direct link. This is not true, if there is at least one undone element in the list. It should be correct (and then the grounder also finds a valid grounding) to just remove the precondition ```(listSeq ?L listStart listEnd)``` here.
This also explains the strange behaviour you have seen: if you uncomment in line 57, you actually always remove all elements of the list - which then allows for ending the recursion, but if you don't you end up with a non-empty list and thus can't end the recursion.

Cheers,
Gregor

**Comment by AlexDmr** [comment]
I feel so sorry (and ashamed) to have bother you with such a trivial thing...
I actually started to encode the removeAll task and then derived the filter one... unfortunatly without having carefully adapt the code ! ^_^
Thanks a lot again for your library.

Btw, not sure if it deserve another issue, I set up a docker container to compile and use pandapi (parser, grounder and engine). I followed the instruction for the compilation of the grounder but it generate an error. The error has been intruduced by the application of the patch (git apply ../0002-makefile.patch). I don't know if it is due to a problem of environment (distribution of linux ?)

If I remove the patch, it can compile.

Here is the dockerfile, maybe it can help someone else :
FROM ubuntu:22.04

RUN apt-get update 
RUN apt-get -y install flex bison nano wget
RUN apt -y install build-essential
RUN apt-get -y install gengetopt git zip cmake 

RUN git clone https://github.com/panda-planner-dev/pandaPIparser.git
RUN cd pandaPIparser && make -j

RUN git clone https://github.com/panda-planner-dev/pandaPIgrounder.git
RUN cd pandaPIgrounder && git submodule init && git submodule update && cd cpddl && make boruvka opts bliss lpsolve && make && cd ../src && make

RUN git clone https://github.com/panda-planner-dev/pandaPIengine.git
RUN cd pandaPIengine && mkdir build && cd build && cmake ../src && make -j

RUN mkdir pandaPIbin
RUN cd pandaPIbin && cp /pandaPIparser/pandaPIparser . && cp /pandaPIgrounder/pandaPIgrounder . && cp /pandaPIengine/build/pandaPIengine . && cp /pandaPIengine/problemSolver.sh .

RUN sed -i 's/local unique_name="--${domain}--${problem}"/local unique_name=$(date +%s%3N)/' /pandaPIbin/problemSolver.sh


Anyway, I close this issue, thanks again for your quick help !
